version: "3.8"

services:
  jenkins-docker:
    image: docker:dind
    environment: 
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - 2376:2376
    privileged: true
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases: 
          - docker

  jenkins-blueocean:
    image: jenkinsci/blueocean
    environment: 
      DOCKER_HOST: tcp://docker:2376 
      DOCKER_CERT_PATH: /certs/client 
      DOCKER_TLS_VERIFY: 1 
    ports:
      - 8080:8080
      - 50000:50000 
    networks:
      jenkins:
    privileged: true
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home

networks: 
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data: