name: Publish to Docker Hub and Heroku
on:    
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: oskwil/dotnettemplate
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        snapshot: true
        default_branch: main

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
        healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
        checkstring: "Healthy"
        rollbackonhealthcheckfailed: true