name: Publish to Docker Hub and Heroku
on:    
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: oskwil/dotnettemplate
        image_tags: latest,${GITHUB_SHA}

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: oskwil-dotnettemplate
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true
        healthcheck: https://oskwil-dotnettemplate.herokuapp.com/health
        checkstring: Healthy
        rollbackonhealthcheckfailed: true
        delay: 60