name: Continuous Integration
on: [pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest    # Sets the build environment a machine with the latest Ubuntu installed
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_USERNAME: OskarTestBot     
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Restore C#
      run: dotnet restore

    - name: Build C#
      run: dotnet build

    - name: Test C#
      run: dotnet test

    - name: Install npm
      working-directory: DotnetTemplate.Web
      run: npm install

    - name: Build npm
      working-directory: DotnetTemplate.Web
      run: npm run build

    - name: Run lint
      working-directory: DotnetTemplate.Web
      run: npm run lint

    - name: Run typescript tests
      working-directory: DotnetTemplate.Web
      run: npm test

    - name: Send Slack Success Message
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: "Yay the tests all pass"

    - name: Send Slack Fail Message
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: "Boo the tests failed"

    - name: Send Slack Cancelled Message
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_MESSAGE: "Who cancelled me? :O"